# Generated by Django 3.1.1 on 2020-11-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='booking_required',
            field=models.BooleanField(default=False),
        ),
    ]
