# Generated by Django 3.1.1 on 2020-11-12 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20201110_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='schedule_required',
        ),
    ]
