# Generated by Django 3.1.1 on 2020-11-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201028_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='booking_required',
            field=models.BooleanField(default=False),
        ),
    ]
