# Generated by Django 3.1.1 on 2020-11-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_booking_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='booking_required',
            new_name='schedule_required',
        ),
    ]
